from pathlib import Path
from typing import Protocol
from uuid import UUID


class ArtifactStorage(Protocol):
    def write_file(self, project_id: UUID, run_id: UUID, path: str, content: bytes) -> None: ...

    def read_file(self, project_id: UUID, run_id: UUID, path: str) -> bytes: ...

    def list_files(self, project_id: UUID, run_id: UUID) -> list[str]: ...

    def delete_tree(self, project_id: UUID, run_id: UUID) -> None: ...

    def resolve_root(self, project_id: UUID, run_id: UUID) -> Path: ...

    def exists(self, project_id: UUID, run_id: UUID, path: str) -> bool: ...
