"""Deterministic mock generator for local/dev without an API key."""

from app.providers.ai.schemas import FileSpec, GenerationRequest, GenerationResult


class MockAIProvider:
    def generate_site(self, request: GenerationRequest) -> GenerationResult:
        title = request.project_name or "Generated Site"
        prompt_excerpt = request.prompt.strip().replace("`", "'")[:280]
        files = [
            FileSpec(
                path="package.json",
                content=f"""{{
  "name": "{_slug(title)}",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {{
    "dev": "vite",
    "build": "tsc -b && vite build",
    "preview": "vite preview"
  }},
  "dependencies": {{
    "react": "^19.0.0",
    "react-dom": "^19.0.0"
  }},
  "devDependencies": {{
    "@tailwindcss/vite": "^4.0.0",
    "@types/react": "^19.0.0",
    "@types/react-dom": "^19.0.0",
    "@vitejs/plugin-react": "^4.3.4",
    "tailwindcss": "^4.0.0",
    "typescript": "~5.7.2",
    "vite": "^6.0.0"
  }}
}}
""",
            ),
            FileSpec(
                path="index.html",
                content=f"""<!doctype html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>{title}</title>
  </head>
  <body>
    <div id="root"></div>
    <script type="module" src="/src/main.tsx"></script>
  </body>
</html>
""",
            ),
            FileSpec(
                path="vite.config.ts",
                content="""import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

export default defineConfig({
  plugins: [react(), tailwindcss()],
})
""",
            ),
            FileSpec(
                path="tsconfig.json",
                content="""{
  "compilerOptions": {
    "target": "ES2022",
    "useDefineForClassFields": true,
    "lib": ["ES2022", "DOM", "DOM.Iterable"],
    "module": "ESNext",
    "skipLibCheck": true,
    "moduleResolution": "bundler",
    "allowImportingTsExtensions": true,
    "isolatedModules": true,
    "moduleDetection": "force",
    "noEmit": true,
    "jsx": "react-jsx",
    "strict": true
  },
  "include": ["src"]
}
""",
            ),
            FileSpec(
                path="src/index.css",
                content="""@import "tailwindcss";

:root {
  font-family: "Segoe UI", system-ui, sans-serif;
  color: #0f172a;
  background: #f8fafc;
}

body {
  margin: 0;
  min-height: 100vh;
}
""",
            ),
            FileSpec(
                path="src/main.tsx",
                content="""import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import App from './App'
import './index.css'

createRoot(document.getElementById('root')!).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
""",
            ),
            FileSpec(
                path="src/App.tsx",
                content=f"""export default function App() {{
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-50 via-sky-50 to-emerald-50 text-slate-900">
      <section className="mx-auto flex min-h-screen max-w-3xl flex-col justify-center px-6 py-16">
        <p className="mb-3 text-sm font-semibold uppercase tracking-[0.2em] text-sky-700">
          AI Website Builder
        </p>
        <h1 className="text-4xl font-bold tracking-tight sm:text-5xl">{title}</h1>
        <p className="mt-4 text-lg leading-relaxed text-slate-600">
          {prompt_excerpt}
        </p>
        <div className="mt-8 flex flex-wrap gap-3">
          <a
            href="#features"
            className="rounded-lg bg-slate-900 px-5 py-2.5 text-sm font-medium text-white transition hover:bg-slate-700"
          >
            Explore
          </a>
          <a
            href="#contact"
            className="rounded-lg border border-slate-300 bg-white px-5 py-2.5 text-sm font-medium text-slate-800 transition hover:border-slate-400"
          >
            Contact
          </a>
        </div>
      </section>
    </main>
  )
}}
""",
            ),
            FileSpec(
                path="README.md",
                content=f"""# {title}

Generated by AI Website Builder.

## Prompt

{prompt_excerpt}

## Scripts

```bash
npm install
npm run dev
```
""",
            ),
            FileSpec(
                path="preview.html",
                content=f"""<!doctype html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <title>{title}</title>
  <style>
    :root {{ font-family: "Segoe UI", system-ui, sans-serif; }}
    body {{ margin: 0; min-height: 100vh; background: linear-gradient(135deg, #f8fafc, #e0f2fe 45%, #ecfdf5); color: #0f172a; }}
    main {{ max-width: 720px; margin: 0 auto; padding: 4rem 1.5rem; display: flex; min-height: 100vh; align-items: center; }}
    .eyebrow {{ letter-spacing: 0.2em; text-transform: uppercase; font-size: 0.75rem; font-weight: 700; color: #0369a1; margin-bottom: 0.75rem; }}
    h1 {{ font-size: clamp(2rem, 5vw, 3rem); line-height: 1.1; margin: 0; }}
    p {{ margin-top: 1rem; font-size: 1.125rem; line-height: 1.6; color: #475569; }}
    .actions {{ margin-top: 2rem; display: flex; gap: 0.75rem; flex-wrap: wrap; }}
    a {{ text-decoration: none; border-radius: 0.5rem; padding: 0.65rem 1.1rem; font-size: 0.875rem; font-weight: 600; }}
    .primary {{ background: #0f172a; color: white; }}
    .ghost {{ background: white; color: #0f172a; border: 1px solid #cbd5e1; }}
  </style>
</head>
<body>
  <main>
    <div>
      <div class="eyebrow">AI Website Builder</div>
      <h1>{title}</h1>
      <p>{prompt_excerpt}</p>
      <div class="actions">
        <a class="primary" href="#">Explore</a>
        <a class="ghost" href="#">Contact</a>
      </div>
    </div>
  </main>
</body>
</html>
""",
            ),
        ]
        return GenerationResult(files=files, summary=f"Mock site generated for: {title}")


def _slug(name: str) -> str:
    cleaned = "".join(ch.lower() if ch.isalnum() else "-" for ch in name).strip("-")
    while "--" in cleaned:
        cleaned = cleaned.replace("--", "-")
    return cleaned or "generated-site"
